name: publish to gh-pages

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Build project
      run: |
        npm install
        npm run build
        
    - name: Set env
      run: |
        echo ::set-env name=PR_NUMBER::$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
    
    - name: Commit files
      run: |
        git config --local user.email "help@htmlacademy.ru"
        git config --local user.name "keksobot"
        git config --local pull.rebase false
        git checkout gh-pages || git checkout --orphan gh-pages
        if [[ -e "$PR_NUMBER" ]]; then
          rm -rf "$PR_NUMBER"
        fi  
        mv build "$PR_NUMBER"
        git add "$PR_NUMBER"
        git commit --allow-empty -m ":heavy_check_mark: Сборка ${{ github.repository }}#"$PR_NUMBER""
    
    - name: Push changes
      run: |
        git push origin gh-pages
        
    - name: Get pullrequest data
      uses: octokit/request-action@v2.0.2
      id: pull_request
      with:
          route: GET /repos/:repository/pulls/:pr_number
          repository: ${{ github.repository }}
          pr_number: ${{ env.PR_NUMBER }}
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Parse pr data
      run: |
        if [[ ${{ fromJson(steps.pull_request.outputs.data).body }} =~ ":boom:" ]]; then
          echo ::set-env name=NEED_UPDATE_BODY::$(echo false)
        else
          echo ::set-env name=NEED_UPDATE_BODY::$(echo true)
        fi
    - name: Update pr description
      if: env.NEED_UPDATE_BODY == true
      uses: octokit/request-action@v2.x
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
          route: POST /repos/:repository/pulls/:pr_number
          repository: ${{ github.repository }}
          pr_number: ${{ env.PR_NUMBER }}
          body: |
            ${{ fromJson(steps.pull_request.outputs.data).body }}
            ---
            :boom: https://${{ github.actor }}.github.io/${{ github.repository }}/${{ env.PR_NUMBER }}/

